### ISSUE TITLE
node engine

### ISSUE THREAD

**Issue by ilaipi** [GrapeoffJS/kindagoose#8]
Hi, is there any code need node v16.16.0?

Can u down the node engine version to v14.0.0 or v16.0.0?

**Comment by GrapeoffJS** [comment]
@ilaipi oh, yeah, I've forgotten to change it when copied it. I have my own template for package.json, but it was not for a library.

**Comment by GrapeoffJS** [comment]
Just downed to `>=12.9.0`

**Comment by ilaipi** [comment]
Great, thanks!
